### ISSUE TITLE
Missing variable initialisation

### ISSUE THREAD

**Issue by ac5113** [xiexh20/HDM#1]
Hello,
I wanted to test the provided HDM checkpoints on the BEHAVE dataset using the script provided. However, I face the error where `pkl_file` path [here](https://github.com/xiexh20/HDM/blob/f3555b2cc8e78a2788288e45c5f545acb4c3b57f/dataset/__init__.py#L132) is not defined anywhere. Could you please tell me where to obtain this path?

**Comment by xiexh20** [comment]
Hi, 

Thank you for your interest. 
The file can be downloaded from https://edmond.mpg.de/file.xhtml?fileId=251365&version=4.0.

I have just made an update in the code, you can see from this commit: https://github.com/xiexh20/HDM/commit/148945322957cfecba7c637dfc44c7d402a37337

**Comment by ac5113** [comment]
Thanks for providing the file.
