### ISSUE TITLE
Installing Problem

### ISSUE THREAD

**Issue by conradguenther** [xiexh20/HDM#3]
Hey,
I try to get the repository working on my PC (I tried Windows but now I am on Debian12). If I follow the instructions in the README I come to the point, where Pytorch3D does not get installed:

![Bildschirmfoto vom 2024-05-31 17-49-59](https://github.com/xiexh20/HDM/assets/92605944/123d55f6-9b07-421f-9a90-85711f4f87cf)

But the workaround with 
```
pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt1110/download.html
```
leads to following error:

![Bildschirmfoto vom 2024-05-31 17-52-16](https://github.com/xiexh20/HDM/assets/92605944/32c1c524-dd2f-49a3-97b0-a54f210cac86)

I tried to install Pytorch3D separately with ```pip install pytorch3d``` and ```pip install pyproject-toml``` but ```python app.py``` is still not working.

![Bildschirmfoto vom 2024-05-31 18-09-52](https://github.com/xiexh20/HDM/assets/92605944/962256c9-be6b-42a2-87a0-12eded495c49)

Could you help me get this repository running?

**Comment by xiexh20** [comment]
Hi, 

Before you run `pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt1110/download.html`, can you install fvcore etc. first? e.g. `pip install fvcore iopath`
