### ISSUE TITLE
About the details of dataset?

### ISSUE THREAD

**Issue by RammusLeo** [xiexh20/HDM#6]
Hi! This is an amazing work. I have a few issues in downloading the ProciGen dataset:

1.  Could you please clarify the structure of each .tar file? Specifically, I’m interested in knowing whether the dataset contains point clouds or annotations of SMPL parameters for the subjects.
2. I’m having difficulty fetching the data directly from Linux. I’ve tried using commands like `wget  https://edmond.mpg.de/api/access/dataset/:persistentId?persistentId=doi:10.17617/3.2VUEUS`, but it appears to download the entire dataset, which is problematic due to my machine’s limited storage capacity. Is there a more efficient way to download only the necessary parts?
3. If possible, would you be able to provide the annotations of SMPL parameters and 6DoF object pose in a separate, independent file? This would be immensely helpful for my purposes.

Thank you so much for your time and assistance. I look forward to your response!

**Comment by xiexh20** [comment]
Hi, thank you for your interest. 

1. As indicated in the [dataset structure](https://github.com/xiexh20/ProciGen?tab=readme-ov-file#dataset-structure), the file includes SMPLH mesh and parameters, same for object, also object mesh and pose parameters. 
2. you might try first click the file to download, and then open downloads in progress in your brower. There should be a place where you can copy the download link for this file and then you can do wget with this link. 
3. yes, I can pack only the pkl files, but it will take some time (~1 week). I will update once it is done. 

Best,
Xianghui

**Comment by RammusLeo** [comment]
Thank you very much for your reply! I will try the methods you mentioned. If there are any updates with the new pkl data, please kindly let me know!
Best regards!
Ao

**Comment by xiexh20** [comment]
@RammusLeo 
All the pickle files are packed in this tar: https://edmond.mpg.de/file.xhtml?fileId=263804&version=6.0
the file name convention is: `<sequence name>/<frame name>+<human|object>.pkl`

Note that the object poses are not rigid transform, it is a uniform scale + rigid transform, for example usage, please see: https://github.com/xiexh20/ProciGen/blob/main/render/blender_rerender.py#L51 

let me know if you have further questions.

**Comment by RammusLeo** [comment]
Thanks for your help! It will be very useful to me!

**Comment by RammusLeo** [comment]
> @RammusLeo All the pickle files are packed in this tar: https://edmond.mpg.de/file.xhtml?fileId=263804&version=6.0 the file name convention is: `<sequence name>/<frame name>+<human|object>.pkl`
> 
> Note that the object poses are not rigid transform, it is a uniform scale + rigid transform, for example usage, please see: https://github.com/xiexh20/ProciGen/blob/main/render/blender_rerender.py#L51
> 
> let me know if you have further questions.

Hi! Sorry to bother again. I have downloaded this annotation file and I found that the shape of pose is (24, 3), which contains only the label of human body. Meanwhile, I notice that you say ProciGen is based on [Human Model: SMPL-H](https://github.com/xiexh20/ProciGen?tab=readme-ov-file#human-model). Is there any annotation for human hands or you just use the [mean hand pose](https://github.com/xiexh20/ProciGen/blob/392f9322bb792a4c2b7e316637dac3428452413d/render/blender_base.py#L43) for training ?
I am looking forward to your reply!

**Comment by xiexh20** [comment]
we use the mean hand pose, see example: https://github.com/xiexh20/ProciGen/blob/main/render/blender_rerender.py#L101
